
import React from 'react';
import { createRoot } from 'react-dom/client';
import { FluentProvider } from '@fluentui/react-components';
import { ThemeProvider, useCodieTheme } from './ThemeContext';
import { CodieChat } from './CodieChat';

// The logoSrc will be set by the webview host via a global variable or replaced at build time
console.log('[Codie] React index.tsx loaded, window.vscode:', window.vscode);


function getSystemTheme(): 'light' | 'dark' {
  if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    return 'dark';
  }
  return 'light';
}

const root = document.getElementById('root');
if (root) {
  // Ensure any auto-generated wrapper element under #root occupies full height
  // Some React/Fluent internals create a wrapper <div> inside #root with autogenerated classes.
  // Inject a global rule to make that child fill available height and use flex column layout.
  const styleId = 'codie-root-wrapper-styles';
  if (!document.getElementById(styleId)) {
    const style = document.createElement('style');
    style.id = styleId;
    style.innerHTML = `#root, #root > div { height: 100% !important; min-height: 0 !important; display: flex !important; flex-direction: column !important; box-sizing: border-box !important; }`;
    document.head.appendChild(style);
  }
  function AppWrapper() {
    const { effectiveTheme } = useCodieTheme();
    return (
      <FluentProvider theme={effectiveTheme}>
        <CodieChat />
      </FluentProvider>
    );
  }

  createRoot(root as HTMLElement).render(
    <ThemeProvider>
      <AppWrapper />
    </ThemeProvider>
  );
}
