const path = require('path');
/** @type {import('webpack').Configuration} */
module.exports = {
  target: 'node',
  mode: 'none',
  entry: './src/extension.ts',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'extension.js',
    libraryTarget: 'commonjs2',
    devtoolModuleFilenameTemplate: '../[resource-path]',
  },
  devtool: 'source-map',
  externals: {
    vscode: 'commonjs vscode',
    'utf-8-validate': 'commonjs utf-8-validate',
    'bufferutil': 'commonjs bufferutil',
    fs: 'commonjs fs',
    path: 'commonjs path',
    util: 'commonjs util',
    child_process: 'commonjs child_process',
    process: 'commonjs process',
    os: 'commonjs os',
    net: 'commonjs net',
    tls: 'commonjs tls',
    stream: 'commonjs stream',
    crypto: 'commonjs crypto',
    zlib: 'commonjs zlib',
    http: 'commonjs http',
    https: 'commonjs https',
    module: 'commonjs module',
    assert: 'commonjs assert',
    constants: 'commonjs constants',
    readline: 'commonjs readline',
    events: 'commonjs events',
    url: 'commonjs url',
    querystring: 'commonjs querystring',
    string_decoder: 'commonjs string_decoder',
    dgram: 'commonjs dgram',
    dns: 'commonjs dns',
    vm: 'commonjs vm',
    perf_hooks: 'commonjs perf_hooks',
    worker_threads: 'commonjs worker_threads',
    v8: 'commonjs v8',
    repl: 'commonjs repl',
    domain: 'commonjs domain',
    punycode: 'commonjs punycode',
    tty: 'commonjs tty',
    sys: 'commonjs sys',
    inspector: 'commonjs inspector',
    buffer: 'commonjs buffer',
    timers: 'commonjs timers',
    console: 'commonjs console',
    cluster: 'commonjs cluster',
    constants: 'commonjs constants',
    'node:fs': 'commonjs fs',
    'node:path': 'commonjs path',
    'node:util': 'commonjs util',
    'node:child_process': 'commonjs child_process',
    'node:process': 'commonjs process',
    'node:os': 'commonjs os',
    'node:net': 'commonjs net',
    'node:tls': 'commonjs tls',
    'node:stream': 'commonjs stream',
    'node:crypto': 'commonjs crypto',
    'node:zlib': 'commonjs zlib',
    'node:http': 'commonjs http',
    'node:https': 'commonjs https',
    'node:module': 'commonjs module',
    'node:assert': 'commonjs assert',
    'node:constants': 'commonjs constants',
    'node:readline': 'commonjs readline',
    'node:events': 'commonjs events',
    'node:url': 'commonjs url',
    'node:querystring': 'commonjs querystring',
    'node:string_decoder': 'commonjs string_decoder',
    'node:dgram': 'commonjs dgram',
    'node:dns': 'commonjs dns',
    'node:vm': 'commonjs vm',
    'node:perf_hooks': 'commonjs perf_hooks',
    'node:worker_threads': 'commonjs worker_threads',
    'node:v8': 'commonjs v8',
    'node:repl': 'commonjs repl',
    'node:domain': 'commonjs domain',
    'node:punycode': 'commonjs punycode',
    'node:tty': 'commonjs tty',
    'node:sys': 'commonjs sys',
    'node:inspector': 'commonjs inspector',
    'node:buffer': 'commonjs buffer',
    'node:timers': 'commonjs timers',
    'node:console': 'commonjs console',
    'node:cluster': 'commonjs cluster',
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'ts-loader',
          },
        ],
      },
    ],
  },
};
