
import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Scaffold a new workspace with VS Code configs.
 * @param rootDir The directory to create the workspace in.
 * @param name The project name.
 * @returns {Promise<{ success: boolean, message: string }>} 
 */
export async function newWorkspace(rootDir: string, name: string): Promise<{ success: boolean, message: string }> {
  if (!rootDir || !name) {
    return { success: false, message: 'rootDir and name are required.' };
  }
  const wsDir = path.join(rootDir, name);
  try {
    await fs.mkdir(wsDir, { recursive: true });
    // Create src, test, .vscode folders
    await Promise.all([
      fs.mkdir(path.join(wsDir, 'src'), { recursive: true }),
      fs.mkdir(path.join(wsDir, 'test'), { recursive: true }),
      fs.mkdir(path.join(wsDir, '.vscode'), { recursive: true })
    ]);
    // Write package.json
    await fs.writeFile(path.join(wsDir, 'package.json'), JSON.stringify({
      name,
      version: '0.0.1',
      scripts: { build: 'tsc', watch: 'tsc --watch' },
      devDependencies: { typescript: '^5.0.0' }
    }, null, 2));
    // Write tsconfig.json
    await fs.writeFile(path.join(wsDir, 'tsconfig.json'), JSON.stringify({
      compilerOptions: {
        target: 'ES2020',
        module: 'commonjs',
        outDir: 'dist',
        rootDir: 'src',
        strict: true,
        esModuleInterop: true
      },
      include: ['src/**/*']
    }, null, 2));
    // Write .vscode/launch.json
    await fs.writeFile(path.join(wsDir, '.vscode', 'launch.json'), JSON.stringify({
      version: '0.2.0',
      configurations: [
        {
          type: 'node',
          request: 'launch',
          name: 'Launch Program',
          program: '${workspaceFolder}/src/index.ts',
          preLaunchTask: 'tsc: build - tsconfig.json',
          outFiles: ['${workspaceFolder}/dist/**/*.js']
        }
      ]
    }, null, 2));
    // Write .vscode/tasks.json
    await fs.writeFile(path.join(wsDir, '.vscode', 'tasks.json'), JSON.stringify({
      version: '2.0.0',
      tasks: [
        {
          label: 'tsc: build - tsconfig.json',
          type: 'shell',
          command: 'tsc',
          args: ['-p', 'tsconfig.json'],
          group: { kind: 'build', isDefault: true },
          problemMatcher: '$tsc'
        }
      ]
    }, null, 2));
    // Write README.md
    await fs.writeFile(path.join(wsDir, 'README.md'), `# ${name}\n\nGenerated by Codie newWorkspace tool.\n`);
    return { success: true, message: `Workspace scaffolded at ${wsDir}` };
  } catch (err: any) {
    return { success: false, message: err?.message || String(err) };
  }
}
